-- Creating Table 1 -- Customer Table
DROP TABLE IF EXISTS Customer;

CREATE TABLE IF NOT EXISTS Customer
(
	Customer_id	VARCHAR(10) PRIMARY KEY, 
	Customer_name VARCHAR(50),
	City VARCHAR(20),
	Customer_type VARCHAR(20)
);

SELECT * FROM Customer;

-- Importing data from csv file
COPY Customer
FROM '/Library/PostgreSQL/18/imports/Customer_Data_For_Joins.csv'
DELIMITER ','
CSV HEADER;

SELECT * FROM Customer;


-- Creating Table 2 : Product Table
DROP TABLE IF EXISTS Product;

CREATE TABLE IF NOT EXISTS Product
(
	Customer_id	VARCHAR(10) PRIMARY KEY, 
	Product	VARCHAR(50),
	Price money
);

SELECT * FROM Product;

-- Importing data from csv file
COPY Product
FROM '/Library/PostgreSQL/18/imports/Product_Table_for_Joins.csv'
DELIMITER ','
CSV HEADER;

SELECT * FROM Product;



-- INNER JOIN
SELECT *
FROM CUSTOMER AS C
INNER JOIN PRODUCT AS P
ON C.CUSTOMER_ID = P.CUSTOMER_ID;

--GET SPECIFIC COLUMNS
SELECT C.CUSTOMER_ID, C.CUSTOMER_NAME, P.PRODUCT, P.PRICE
FROM CUSTOMER AS C
INNER JOIN PRODUCT AS P
ON C.CUSTOMER_ID = P.CUSTOMER_ID;



--LEFT JOIN
SELECT * FROM CUSTOMER AS C
LEFT JOIN PRODUCT AS P
ON C.CUSTOMER_ID = P.CUSTOMER_ID;

--GET SPECIFIC COLUMNS
SELECT C.CUSTOMER_ID, C.CUSTOMER_NAME, P.PRODUCT, P.PRICE
FROM CUSTOMER AS C
LEFT JOIN PRODUCT AS P
ON C.CUSTOMER_ID = P.CUSTOMER_ID;



--RIGHT JOIN
SELECT * FROM CUSTOMER 
RIGHT JOIN PRODUCT
ON CUSTOMER.CUSTOMER_ID = PRODUCT.CUSTOMER_ID;

--GET SPECIFIC COLUMNS
SELECT C.CUSTOMER_ID, C.CUSTOMER_NAME, P.PRODUCT, P.PRICE
FROM CUSTOMER AS C
RIGHT JOIN PRODUCT AS P
ON C.CUSTOMER_ID = P.CUSTOMER_ID;



--FULL JOIN
SELECT * FROM CUSTOMER AS C
FULL OUTER JOIN PRODUCT AS P
ON C.CUSTOMER_ID = P. CUSTOMER_ID;

--GET SPECIFIC COLUMNS
SELECT C.CUSTOMER_ID, P.CUSTOMER_ID, C.CUSTOMER_NAME, P.PRODUCT, P.PRICE
FROM CUSTOMER AS C
FULL OUTER JOIN PRODUCT AS P
ON C.CUSTOMER_ID = P.CUSTOMER_ID;


--JOIN WITH WHERE CLAUSE
SELECT C.CUSTOMER_NAME, P.PRODUCT, P.PRICE
FROM CUSTOMER AS C
LEFT JOIN PRODUCT AS P
ON C.CUSTOMER_ID = P.CUSTOMER_ID
WHERE P.CUSTOMER_ID IS NOT NULL;

SELECT * FROM CUSTOMER AS C
RIGHT JOIN PRODUCT AS P
ON C.CUSTOMER_ID=P.CUSTOMER_ID
WHERE C.CUSTOMER_ID IS NOT NULL;

SELECT C.CUSTOMER_NAME, P.PRODUCT, P.PRICE
FROM CUSTOMER AS C
FULL OUTER JOIN PRODUCT AS P
ON C.CUSTOMER_ID = P.CUSTOMER_ID
WHERE P.CUSTOMER_ID IS NOT NULL AND C.CUSTOMER_ID IS NOT NULL;
