--regular way
DROP TABLE IF EXISTS student2;

CREATE TABLE student2(
	"ID" INT PRIMARY KEY,
	"Name" varchar(20),
	"Age" INT
);

INSERT INTO student2 VALUES(1, 'Uday', 20);
INSERT INTO student2 VALUES(2, 'knay', 20);
INSERT INTO student2 VALUES(3, 'stud', 20);

select * from student2;


--auto assign ID using IDENTITY constraint
DROP TABLE IF EXISTS student2;

CREATE TABLE student2(
	"ID" INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	"Name" varchar(20),
	"Age" INT
);

INSERT INTO student2 VALUES(DEFAULT, 'Uday', 20);
INSERT INTO student2 VALUES(DEFAULT, 'knay', 20);
INSERT INTO student2 VALUES(DEFAULT, 'stud', 20);

select * from student2;


--TO ALLOW MANUAL OVERRIDE
DROP TABLE IF EXISTS student2;

CREATE TABLE student2(
	"ID" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"Name" varchar(20),
	"Age" INT
);

INSERT INTO student2 VALUES(DEFAULT, 'Uday', 20);
INSERT INTO student2 VALUES(DEFAULT, 'knay', 20);
INSERT INTO student2 VALUES(23, 'stud', 20);

select * from student2;


--START WITH and INCREMENT BY
DROP TABLE IF EXISTS student2;

CREATE TABLE student2(
	"ID" INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY 
		(START WITH 1 INCREMENT BY 2),
	"Name" varchar(20),
	"Age" INT
);

INSERT INTO student2 VALUES(DEFAULT, 'Uday', 20);
INSERT INTO student2 VALUES(DEFAULT, 'knay', 20);
INSERT INTO student2 VALUES(DEFAULT, 'stud', 20);

select * from student2;