DROP TABLE IF EXISTS SALES_DATA2;

CREATE TABLE IF NOT EXISTS SALES_DATA2
(
order_id		varchar(20) PRIMARY KEY,
order_date		date,
ship_date		date,
ship_mode		varchar(20),
customer_id		varchar(20),
customer_name	varchar(50),
segment			varchar(20),
country			varchar(20),
city			varchar(40),
state			varchar(40),
postal_code		int,
region			varchar(10),
product_id		varchar(20),
category		varchar(20),
sub_category	varchar(20),
product_name	varchar(200),
sales_$			money,
quantity		int,
profit_$		money

);

SELECT * FROM SALES_DATA2;

--data is directly imported using IMPORT/EXPORT option
SELECT * FROM SALES_DATA2;


-- 1 ) UPPER FUNCTION
SELECT UPPER(CUSTOMER_NAME) FROM SALES_DATA2;


-- 2 ) LOWER FUNCTION
SELECT LOWER(CUSTOMER_NAME) FROM SALES_DATA2;


-- 3 ) LENGTH FUNCTION
SELECT CUSTOMER_NAME, LENGTH(CUSTOMER_NAME) FROM SALES_DATA;2


-- 4 ) CONCAT FUNCTION
SELECT SHIP_DATE, SHIP_MODE, CONCAT(SHIP_DATE, SHIP_MODE) FROM SALES_DATA2;

SELECT SHIP_DATE, SHIP_MODE, SHIP_DATE || SHIP_MODE FROM SALES_DATA2;


-- 5 ) REPLACE FUNCTION
SELECT REGION, REPLACE(REGION, 'Central', 'North') FROM SALES_DATA2;


-- 6 ) SUBSTRING FUNCTION
SELECT CUSTOMER_NAME, SUBSTRING(CUSTOMER_NAME,1,6) FROM SALES_DATA2;


-- 7 ) STRPOS FUNCTION
SELECT CUSTOMER_NAME, STRPOS(CUSTOMER_NAME, ' ') FROM SALES_DATA2;

SELECT CUSTOMER_NAME, POSITION(' ' IN CUSTOMER_NAME) FROM SALES_DATA2;


-- GET SEPARATE FIRST NAME FROM CUSTOMER NAME
SELECT CUSTOMER_NAME, SUBSTRING(CUSTOMER_NAME, 1, POSITION(' ' IN CUSTOMER_NAME)) FROM SALES_DATA2;


-- GET SEPARATE LAST NAME FROM CUSTOMER NAME
SELECT CUSTOMER_NAME, SUBSTRING(CUSTOMER_NAME, STRPOS(CUSTOMER_NAME, ' ')+1, LENGTH(CUSTOMER_NAME)) FROM SALES_DATA2;

-- TO GET LAST WORD FROM ANY LONG STRING
SELECT CUSTOMER_NAME, SPLIT_PART(CUSTOMER_NAME, ' ', -1) AS last_name FROM SALES_DATA2;


SELECT SPLIT_PART('UDAY NANDKUMAR ZAWARE', ' ', -1); 
SELECT SPLIT_PART('UDAY NANDKUMAR ZAWARE', ' ', 1); 
SELECT SPLIT_PART('UDAY NANDKUMAR ZAWARE', ' ', 2); 



